name: commit-to-tg

on:
  push:
    branches:
      - main
      - develop
      - gabriella

jobs:
  sendMessage:
    name: –û—Ç–ø—Ä–∞–≤–∫–∞ —Å–æ–æ–±—â–µ–Ω–∏—è —Å –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏–µ–π –æ –∫–æ–º–º–∏—Ç–µ –≤ —á–∞—Ç Telegram
    runs-on: ubuntu-latest
    steps:
      - name: –û—Ç–ø—Ä–∞–≤–∫–∞ —Å–±—â.
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_GROUP }}
          token: ${{ secrets.TG_BOT_TOKEN }}
          format: markdown
          message: |
            üìå ${{ github.event.commits[0].message }}
            üë®‚Äçüíª [${{ github.actor }}](https://github.com/${{ github.actor }}) / telegram: @${{ github.actor }}
            üóÇ [${{ github.repository }}](https://github.com/${{ github.repository }})
            #Ô∏è‚É£ [${{github.sha}}](https://github.com/${{ github.repository }}/commit/${{github.sha}})
            ü§ñ ${{github.workflow}}